<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="elbow_module_snake_monster"
               params="name child length1 twist1 length2 twist2">
  <link name="${name}__INPUT_INTERFACE">
    <visual>
      <origin xyz="0 0 ${length1/2}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${length1}" radius=".0254" />
      </geometry>
      <xacro:silver_material/>
    </visual>
    <visual>
      <origin xyz="${0.0782-0.0508} ${-0.0508-0.0274} ${length1-0.007}" rpy="1.57075 0 ${twist1}" />
      <geometry>
        <mesh filename="package://snake_monster/meshes/elbow_corner.stl"/>
      </geometry>
      <xacro:silver_material/>
    </visual>
    <collision>
      <origin xyz="0 0 ${length1/2}" rpy="0 0 0" />
      <geometry>
    	<cylinder length="${length1}" radius=".0254" />
      </geometry>
    </collision>
    <collision>
      <origin xyz="0 -0.01 ${length1+.012}" rpy="0 0 0" />
      <geometry>
	<sphere radius="${length1}" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${length1+.02}" rpy="0 0 0" />
      <mass value=".045"/>
      <inertia ixx="${.045/12.0*(3*.0254**2+length1**2)}" iyy="${.045/12.0*(3*.0254**2+length1**2)}" izz="${.045/2.0*.0254**2}" ixy="0" ixz="0" iyz="0" />
    </inertial>
  </link>

  <xacro:collar parent="${name}__INPUT_INTERFACE"/>

  <joint name="${name}__MID_ELBOW_JOINT" type="fixed">
    <parent link="${name}__INPUT_INTERFACE"/>
    <child link="${name}__AFTER_CORNER_BODY"/>
    <origin xyz="0 0 ${length1+.0254}" rpy="${-PI/2} 0 ${twist1}"/>
  </joint>

  <link name="${name}__AFTER_CORNER_BODY">
    <visual>
      <origin xyz="0 0 ${(length2/2)+.0254}" rpy="0 0 0" />
      <geometry>
        <cylinder length="${length2}" radius=".0254" />
      </geometry>
      <xacro:silver_material/>
    </visual>
    <collision>
      <origin xyz="0 0 ${(length2/2)+.0254}" rpy="0 0 0" />
      <geometry>
    	<cylinder length="${length2}" radius=".0254" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${(length2/2)+.0254}" rpy="0 0 0" />
      <mass value=".065"/>
      <inertia ixx="${.065/12.0*(3*.0254**2+length1**2)}" iyy="${.065/12.0*(3*.0254**2+length1**2)}" izz="${.065/2.0*.0254**2}" ixy="0" ixz="0" iyz="0" />
    </inertial>
  </link>

  <joint name="${name}__OUTPUT_INTERFACE" type="fixed">
    <parent link="${name}__AFTER_CORNER_BODY"/>
    <child link="${child}__INPUT_INTERFACE"/>
    <origin xyz="0 0 ${length2+.0254}" rpy="0 0 ${twist2}"/>
  </joint>

  </xacro:macro>
</robot>
